apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml

images:
  - name: 197179613039.dkr.ecr.ap-northeast-2.amazonaws.com/gateway/api
    newTag: build-2-1
  - name: 197179613039.dkr.ecr.ap-northeast-2.amazonaws.com/ai-chat/api
    newTag: build-1-1
  - name: 197179613039.dkr.ecr.ap-northeast-2.amazonaws.com/authentication/api
    newTag: bootstrap
  - name: 197179613039.dkr.ecr.ap-northeast-2.amazonaws.com/content/api
    newTag: build-1-1
  - name: 197179613039.dkr.ecr.ap-northeast-2.amazonaws.com/graph-rag/api
    newTag: build-4-1

replicas:
  - name: gateway-api
    count: 2
