apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: "3.5.0"
    helm:
      valuesObject:
        clusterName: lore-sentry-k8s
        region: ap-northeast-2
        vpcId: vpc-0affa34ee2ad890f9

        replicaCount: 2

        serviceAccount:
          create: true
          name: aws-load-balancer-controller

        ingressClass: alb
        ingressClassParams:
          create: true
          spec:
            group:
              name: lore-sentry
            scheme: internet-facing
            targetType: ip
            ipAddressType: ipv4
            certificateArn:
              - arn:aws:acm:ap-northeast-2:197179613039:certificate/43ac7f41-484e-46b5-8e08-15a635db5296
            sslRedirectPort: "443"
            tags:
              - key: Project
                value: lore-sentry
              - key: ManagedBy
                value: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

  ignoreDifferences:
    - kind: Secret
      name: aws-load-balancer-tls
      jqPathExpressions:
        - .data

    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: aws-load-balancer-webhook
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle

    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: aws-load-balancer-webhook
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle