apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://github.com/soma-lorekeeper/loresentry-gitops.git
    targetRevision: main
    path: workload/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
