apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 루트 애플리케이션이 바라보는 진입점.
# 여기에 등록된 Application 매니페스트들이 실제 배포 단위가 된다.
namespace: argocd

resources:
  - platform-applications.yaml
  - workload-applications.yaml
