apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lore-sentry-api
  namespace: lore-sentry
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: <ACM-인증서-ARN>

    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: "200-399"
spec:
  ingressClassName: alb
  rules:
    - host: api.loresentry.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lore-sentry-api
                port:
                  number: 80
