apiVersion: v1
kind: Service
metadata:
  name: lore-sentry-api
  namespace: lore-sentry
spec:
  type: ClusterIP
  selector:
    app: lore-sentry-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
